export const paths = {
  home: "/arizona-notary-exam/",
  hub: "/arizona/",
  practice: "/arizona-notary-practice-test/",
  practiceFree: "/arizona-notary-practice-test-free/",
  questions: "/arizona-notary-exam-questions/",
  study: "/arizona-notary-study-guide/",
  examPrep: "/arizona-notary-exam-prep/",
  guidesIndex: "/arizona-notary-exam-guides/",
  howHard: "/how-hard-is-the-arizona-notary-exam/",
  passingScore: "/arizona-notary-exam-passing-score/",
  questionCount: "/how-many-questions-on-the-arizona-notary-exam/",
  examRequirements: "/arizona-notary-exam-requirements/",
  fees: "/arizona-notary-fees/",
  bond: "/arizona-notary-bond-requirements/",
  ron: "/arizona-remote-online-notary-requirements/",
  examFaq: "/arizona-notary-exam-faq/",
  cram: "/arizona-notary-exam-cram-sheet/",
  mistakesGuide: "/arizona-notary-exam-mistakes-to-avoid/",
  courses: "/arizona-notary-courses/",
  training: "/arizona-notary-training/",
  flashcards: "/arizona/flashcards/",
  laws: "/arizona/new-laws/",
  become: "/arizona/become-a-notary/",
  examGuide: "/arizona-notary-exam-prep/",
  topic: (id: string) => `/arizona/questions/${id}/`,
  law: (slug: string) => `/arizona/laws/${slug}/`,
  login: "/login/",
  register: "/register/",
  forgot: "/forgot-password/",
  reset: "/reset-password/",
  verify: "/verify-email/",
  dashboard: "/dashboard/",
  account: "/account/",
  profile: "/account/profile/",
  referrals: "/account/referrals/",
  billing: "/account/billing/",
  accountDelete: "/account/delete/",
  mistakes: "/wrong-answers/",
  pricing: "/pricing/",
  contact: "/contact/",
  privacy: "/legal/privacy/",
  terms: "/legal/terms/",
  cookies: "/legal/cookies/",
  refund: "/legal/refund/",
  affiliate: "/legal/affiliate-disclosure/",
  disclaimer: "/legal/disclaimer/",
} as const;
